matrix:
  include:    
    - language: c  
      sudo: false # only for faster builds  
      compiler:
        - clang
        - gcc
      script:  
        - gcc -o test test.c  
        - ./test  
        - gcc -o fact fact.c
        - ./fact
    - language: cpp  
      compiler: gcc  
      dist: trusty  
      before_install:  
       - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
       - sudo apt-get update -qq  
      install:   
       - sudo apt-get install -qq g++-6  
       - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90  
      script:   
        - g++ swap.cpp -std=c++17 -o travis_gcc_cpp17  
        - ./travis_gcc_cpp17 
        - g++ pyra.cpp -std=c++17 -o travis_gcc_cpp17 
        - ./travis_gcc_cpp17 
    - language: java
      jdk: oraclejdk8
      script: 
        - javac test.java
        - java test
        - javac Fact.java
        - java Fact
    - language: python
      python: 3.6
      cache: pip
      before_script:
       - easy_install distribute
       - pip install -r requirements.txt
      script: 
       - python test.py
       - python fact.py
    - language: ruby
      sudo: false
      script: 
       - ruby hello.rb
       - ruby test.rb
      rvm:
       - 1.9.3
       - 2.0
       - 2.1
       - 2.2
       - 2.3
       - ruby-head
      notifications:
      email: false
    - language: php
      php:
       - 5.5
       - 5.6
       - 7.0
      branches:
        only:
          master
      before_install:
        - travis_retry composer self-update
      script: phpunit --exclude-group FITS --bootstrap vendor/test.php tests
