matrix:
  include:
    - language: c
      sudo: false # only for faster builds
      script:
        - gcc -o test test.c
        - ./test
    - language: cpp
      compiler: gcc
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install: 
        - sudo apt-get install -qq g++-6
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
      script: 
        - g++ swap.cpp -std=c++17 -o travis_gcc_cpp17
        - ./travis_gcc_cpp17
    - language: java
      jdk: oraclejdk8
      script: 
        - javac test.java
        - java test
        - javac Fact.java
        - java Fact
    - language: python
      python: 3.6
      cache: pip
      before_script:
       - easy_install distribute
       - pip install -r requirements.txt
      script: 
       - python test.py
       - python fact.py
