matrix:
  include:    
    - language: c  
      sudo: false # only for faster builds  
      compiler:
        - clang
        - gcc
      script:  
        - gcc -o test test.c  
        - ./test  
        - gcc -o fact fact.c
        - ./fact
    - language: cpp  
      compiler: gcc  
      dist: trusty  
      before_install:  
       - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
       - sudo apt-get update -qq  
      install:   
       - sudo apt-get install -qq g++-6  
       - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90  
      script:   
        - g++ swap.cpp -std=c++17 -o travis_gcc_cpp17  
        - ./travis_gcc_cpp17 
        - g++ pyra.cpp -std=c++17 -o travis_gcc_cpp17 
        - ./travis_gcc_cpp17 
    - language: java
      jdk: oraclejdk8
      script: 
        - javac test.java
        - java test
        - javac Fact.java
        - java Fact
    - language: python
      python: 3.6
      cache: pip
      before_script:
       - easy_install distribute
       - pip install -r requirements.txt
      script: 
       - python test.py
       - python fact.py
    - language: ruby
      sudo: false
      script: 
       - ruby hello.rb
       - ruby test.rb
      rvm:
       - 1.9.3
       - 2.0
       - 2.1
       - 2.2
       - 2.3
       - ruby-head
      notifications:
      email: false
    - language: php
      php:
       - "7.2"
       - "7.1"
       - "7.0"
       - "5.6"
       - "5.5"
       - "5.4"
       - "nightly"
      sudo: false
      install:
        - travis_retry composer self-update && composer --version
  # We have to supply the branch alias here again as travis checks out a commit hash and therefore destroys the
  # circular dependency phpcq/all-tasks -> phpcq/autoload-validation -> phpcq/all-tasks.
        - >
          if [ "x${TRAVIS_TAG}" != "x" ]; then
            COMPOSER_ROOT_VERSION=${TRAVIS_TAG} travis_retry composer update --prefer-dist --no-interaction;
          else
            COMPOSER_ROOT_VERSION=dev-${TRAVIS_BRANCH} travis_retry composer update --prefer-dist --no-interaction;
         fi
      script: ant -keep-going
      allow_failure:
        - php: "7.0"
        - php: "nightly"
