matrix:
  include:    
    - language: c  
      sudo: false # only for faster builds  
      script:  
        - gcc -o test test.c  
        - ./test  
    - language: cpp
# Compiler selection
      compiler:
        - clang
        - gcc
# Build steps
      script:
        - mkdir build
        - cd build
        - cmake .. && make
    - language: java
      jdk: oraclejdk8
      script: 
        - javac test.java
        - java test
        - javac Fact.java
        - java Fact
    - language: python
      python: 3.6
      cache: pip
      before_script:
       - easy_install distribute
       - pip install -r requirements.txt
      script: 
       - python test.py
       - python fact.py
