matrix:
  include:
    - language: c
      sudo: false # only for faster builds
      script:
        - gcc -o test test.c
        - ./test
     - language: python
       python:
        - "3.6"
       script: 
         - python test.py
     - language: cpp
       compiler: gcc
       dist: trusty
       before_install:
         - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
         - sudo apt-get update -qq
       install: 
         - sudo apt-get install -qq g++-6
         - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
       script: 
         - g++ swap.cpp -std=c++17 -o travis_gcc_cpp17
         - ./travis_gcc_cpp17
     - language: java
       jdk: oraclejdk8
       script: 
         - javac test.java
         - java test
